testFramework: espresso

# Path to the app's .apk
app: 51

# Path to the test runner app's .apk
test: ../apps/ImagineBanking-1.2-test.apk

# Path where XML test reports will be saved.
xmlFolder: ./xml-reports

# Define a list of devices on which the tests should be executed.
devices:

# Device 1 example: minimal configuration.
# Only specify a DC (either EU or US).
- datacenter: EU
  testname: IB_LoginTest

# Device 2 example: Static Allocation.
- datacenter: EU
  device: Samsung_Galaxy_S8_real
  testname: IB_LoginTest

# Device 3 example: Dynamic Allocation.
- datacenter: EU
  deviceNameQuery: Samsung Galaxy.*
  platformVersion: 8
  testname: IB_LoginTest

- datacenter: EU
  deviceNameQuery: Samsung Galaxy.*
  platformVersion: 7
  testname: IB_LoginTest

- datacenter: EU
  deviceNameQuery: Google Pixel
  testname: IB_LoginTest

- datacenter: EU
  deviceNameQuery: Google Pixel XL
  testname: IB_LoginTest

- datacenter: EU
  deviceNameQuery: Google Pixel 2
  testname: IB_LoginTest

- datacenter: EU
  deviceNameQuery: Google Pixel 2 XL
  testname: IB_LoginTest

- datacenter: EU
  deviceNameQuery: Google Pixel 3
  testname: IB_LoginTest

- datacenter: EU
  deviceNameQuery: Google Pixel 3 XL
  testname: IB_LoginTest
